# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0003_auto_20161218_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friendsfriend', to='belt_app.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usersfriend', to='belt_app.User')),
            ],
        ),
    ]
