# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0004_friend_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_list',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friendsid', to='belt_app.User'),
        ),
        migrations.AlterField(
            model_name='friend_list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usersid', to='belt_app.User'),
        ),
    ]
